// pages/index.vue
<template>
  <div class="container">
    <GanahaBirthday
      :birthdayNumbers="birthdayNumbers"/>
    <Incremental
      v-for="(birthdayNumber, i) in birthdayNumbers"
      :key="String(i)"
      :incrementalObj="propObj"
      :digits="i"
      @countUp="setNumbers"
    />
  </div>
</template>

<script lang="ts">
import { createComponent, ref } from '@vue/composition-api'
import GanahaBirthday from '~/components/GanahaBirthday'
import Incremental from '~/components/Incremental'

export default createComponent({
  components: {
    GanahaBirthday,
    Incremental
  },
  setup() {
    let birthdayNumbers = ref([0,0,0,0])

    const setNumbers = (payload: any) => {
      birthdayNumbers.value[payload.digits] = payload.count
    }

    const propObj = {
      buttonText: '＋',
      value: 0
    }

    return { propObj, birthdayNumbers, setNumbers }
  }
})
</script>

<style>
.container {
  margin: 0 auto;
  min-height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
  text-align: center;
}
</style>

// pages/index.tsx
import { createComponent, reactive, computed, onMounted } from '@vue/composition-api'
import Increment from '../components/Increment'

interface State {
  count: number
  double: number
}

function increment(state: any) {
  state.count++
}

export default createComponent({
  components: {
    Increment
  },
  setup() {
    const state: State = reactive({
      count: 0,
      double: computed(() => state.count * 2)
    })

    return () => (
      <div style="margin: 0 auto; min-height: 100vh; display: flex; justify-content: center; align-items: center;">
        <Increment state={state} increment={increment} />
      </div>
    )
  }
})
